# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-template

on: [push, workflow_dispatch]
env:
  GITHUB_WORKSPACE: ${{ github.workspace }} 

jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        dotnet-version: [ '6.0.x','7.0','8.0' ]
        template-number: ['01','02','03','04','05','06']

    steps:
      - uses: actions/checkout@master
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Create build direcotry
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Universal 
          Get-Module Universal -ListAvailable
          New-Item -Path ${{ env.GITHUB_WORKSPACE }}\build -Force -ItemType Directory
          New-Item -Path ${{ env.GITHUB_WORKSPACE }}\build\${{ matrix.template-number }} -Force -ItemType Directory
          Copy-Item -Path ${{ env.GITHUB_WORKSPACE }}\templates\store-${{ matrix.template-number}} -Destination ${{ env.GITHUB_WORKSPACE }}\build\${{ matrix.template-number }} -Force -Recurse
        shell: pwsh
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
